PUT http://localhost:4004/api/patients/c752bef8-d2bf-4d86-960d-d4725806c6c7
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe auth test updated",
  "email": "test7@gmail.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09"
}

